version: '3'
services:
  app:
    build: 
      context: '.'
      dockerfile: 'app.Dockerfile'
      args:
        - user_app=maxim
    hostname: app
    volumes:
      - .:/app
    networks:
      - aviasales
    ports:
      - "8080:3001"
    depends_on:
      - mysql

    environment:
      RAILS_ENV: development
    entrypoint: "bundle exec puma -C config/puma.rb config.ru"
  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
    networks:
      - aviasales
networks:
  aviasales:
