default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root")%>
  password:  <%= ENV.fetch("MYSQL_PASSWORD", "" )%>
  host: <%= ENV.fetch("MYSQL_HOST", "127.0.0.1") %>
development:
  <<: *default
  database: aviasales_app_development
test:
  <<: *default
  database: aviasales_app_test
#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
production:
  <<: *default
  database: aviasales_app_production
  username: test_app
  password: <%= ENV['TEST_APP_DATABASE_PASSWORD'] %>
